---
- name: "Ensure ~/.config exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: '0755'

- name: "Ensure ~/.cache exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.cache"
    state: directory
    mode: '0755'

- name: "Ensure ~/.local/share exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share"
    state: directory
    mode: '0755'

- name: "Ensure ~/.local/state exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/state"
    state: directory
    mode: '0755'

- name: "Ensure ~/.local/bin exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0755'

- name: "Create symlink for scripts"
  ansible.builtin.file:
    src: "{{ role_path }}/files/scripts"
    dest: "{{ ansible_user_dir }}/.local/bin"
    state: link
    force: true

- name: "Create symlink for .bashrc"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    state: link
    force: yes

- name: "Create symlink for .profile"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.profile"
    dest: "{{ ansible_user_dir }}/.profile"
    state: link
    force: yes

- name: "Create symlink for bash.bashrc"
  ansible.builtin.file:
    src: "{{ role_path }}/files/bash.bashrc"
    dest: "/etc/bash.bashrc"
    state: link
    force: yes
  become: true

- name: "Create symlink for profile"
  ansible.builtin.file:
    src: "{{ role_path }}/files/profile"
    dest: "/etc/profile"
    state: link
    force: yes
  become: true

- name: "Create symlink for .bash_aliases"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.bash_aliases"
    dest: "{{ ansible_user_dir }}/.bash_aliases"
    state: link
    force: yes

- name: "Create symlink for .bash_env"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.bash_env"
    dest: "{{ ansible_user_dir }}/.bash_env"
    state: link
    force: yes

