---
- name: "{{ role_name }} | Ensure ~/.config exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: '0755'

- name: "{{ role_name }} | Ensure ~/.cache exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.cache"
    state: directory
    mode: '0755'

- name: "{{ role_name }} | Ensure ~/.local/share exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share"
    state: directory
    mode: '0755'

- name: "{{ role_name }} | Ensure ~/.local/state exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/state"
    state: directory
    mode: '0755'

- name: "{{ role_name }} | Ensure ~/.local/bin exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0755'

- name: "{{ role_name }} | Create symlink for scripts/bin"
  ansible.builtin.file:
    src: "{{ role_path }}/files/scripts/bin"
    dest: "{{ ansible_user_dir }}/.local/bin"
    state: link
    force: true

- name: "{{ role_name }} | Create symlink for drproxy"
  ansible.builtin.file:
    src: "{{ role_path }}/files/scripts/sbin/drproxy"
    dest: "/usr/local/bin/drproxy"
    state: link
    force: true
  become: true

- name: "{{ role_name }} | Create symlink for .bashrc"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    state: link
    force: yes

- name: "{{ role_name }} | Create symlink for .profile"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.profile"
    dest: "{{ ansible_user_dir }}/.profile"
    state: link
    force: yes

- name: "{{ role_name }} | Create symlink for bash.bashrc"
  ansible.builtin.file:
    src: "{{ role_path }}/files/bash.bashrc"
    dest: "/etc/bash.bashrc"
    state: link
    force: yes
  become: yes

- name: "{{ role_name }} | Create symlink for profile"
  ansible.builtin.file:
    src: "{{ role_path }}/files/profile"
    dest: "/etc/profile"
    state: link
    force: yes
  become: yes

#- name: "{{ role_name }} | Create symlink for resolv.conf"
#  ansible.builtin.copy:
#    src: "{{ role_path }}/files/resolv.conf"
#    dest: "/etc/resolv.conf"
#    force: yes
#    mode: '0644'
#  become: yes

#- name: "{{ role_name }} | Create symlink for environment"
#  ansible.builtin.file:
#    src: "{{ role_path }}/files/environment"
#    dest: "/etc/environment"
#    state: link
#    force: yes
#  become: yes

- name: "{{ role_name }} | Create symlink for wsl.conf"
  ansible.builtin.file:
    src: "{{ role_path }}/files/wsl.conf"
    dest: "/etc/wsl.conf"
    state: link
    force: yes
  become: yes

- name: "{{ role_name }} | Create symlink for .bash_aliases"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.bash_aliases"
    dest: "{{ ansible_user_dir }}/.bash_aliases"
    state: link
    force: yes

- name: "{{ role_name }} | Create symlink for .bash_env"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.bash_env"
    dest: "{{ ansible_user_dir }}/.bash_env"
    state: link
    force: yes

