- name: Bootstrap development environment
  hosts: localhost
  tasks:
  - name: Install packages with apt
    become: yes
    ansible.builtin.apt:
      name:
        - git
        - neovim
      state: present
