#!/bin/bash

# ____       _   _         
#|  _ \ __ _| |_| |__  ___ 
#| |_) / _` | __| '_ \/ __|
#|  __/ (_| | |_| | | \__ \
#|_|   \__,_|\__|_| |_|___/
#                          
SSH_DIR="$HOME/.ssh"

mkdir -p $SSH_DIR
chmod 700 $SSH_DIR
chmod 644 $SSH_DIR/id_docker.pub
chmod 600 $SSH_DIR/id_docker
eval $(ssh-agent -s)
ssh-add $SSH_DIR/id_docker
cat $SSH_DIR/id_docker.pub >> $SSH_DIR/authorized_keys

ssh -T git@github.com
