#!/bin/bash

case $1 in
    on)

cat > /etc/environment <<END
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export http_proxy="http://internet.ford.com:83"
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export no_proxy="localhost,127.0.0.1,.ford.com,.local,.testing,.internal,.googleapis.com,19.0.0.0/8,136.1.0.0/16,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
export FTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
export HTTP_PROXY=$http_proxy
export NO_PROXY=$no_proxy
END

cat > /etc/resolv.conf <<END
# Ford Name Servers (used while on VPN)
search ppp.ford.com
nameserver 19.13.0.246
nameserver 19.69.0.246
END
        ;;
    off)
cat > /etc/environment <<END
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
END
windows_ip=$(ip route | grep default | awk '{print $3}')
cat > /etc/resolv.conf <<END
nameserver $windows_ip
nameserver 8.8.8.8
nameserver 8.8.4.4
END
        ;;
esac
