#!/bin/bash

USER='ahmed'
# Define source and destination
BACKUP_FOLDER="$HOME/backups"
REMOTE_FOLDER="$USER@192.168.50.2:/volume1/homes/ahmed/linux/backups"
SOURCE=$BACKUP_FOLDER
DESTINATION=$REMOTE

# Parse arguments

dry_run=true
while getopts "n" opt; do
  case $opt in
    n) dry_run=true ;;
    *) echo "Usage: $0 [-n]"; exit 1 ;;
  esac
done

# Rsync options
OPTIONS="-avz -e ssh"
if [ "$dry_run" = true ]; then
  OPTIONS="$OPTIONS --dry-run"
fi

# Run rsync
rsync $OPTIONS "$SOURCE" "$DESTINATION"

# Check exit status
if [ $? -eq 0 ]; then
    echo "Backup completed successfully."
else
    echo "Backup encountered errors." >&2
    exit 1
fi

