- name: "{{ role_name }} : Copy SSH private keys"
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: '0600'
  loop: "{{ ssh_key | default({}) | dict2items }}"
  loop_control:
    loop_var: ssh_key_item
  when: "'pub' not in ssh_key_item.key"  # Skip .pub files
  no_log: true

- name: "{{ role_name }} : Copy SSH public keys"
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: '0644'
  loop: "{{ ssh_key | default({}) | dict2items }}"
  loop_control:
    loop_var: ssh_key_item
  when: "'pub' in ssh_key_item.key"  # Skip .pub files
  no_log: true

