---
- name: "{{ ansible_distribution }} : Copy SSH keys"
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: 0600

  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/dotfiles.pub') }}"
