---
- name: "{{ ansible_distribution }} : Update and Upgrade Package Manager"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: "{{ ansible_distribution }} : Install"
  ansible.builtin.apt:
    name:
      - neovim
      - tmux
    state: present
  become: true

