---
- name: "{{ role_name }} | Update and Upgrade Package Manager"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: "{{ role_name }} | Install"
  ansible.builtin.apt:
    name:
      - ncdu
      - nala
    state: present
  become: true

