---
- name: "{{ ansible_distribution }} : Dependencies"
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - git
      - build-essential
      - software-properties-common
    state: present
    update_cache: yes

- name: "{{ ansible_distribution }} : Clone Repository"
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "/usr/local/src/neovim"
    version: "v0.10.3"
    force: yes

- name: "{{ ansible_distribution }} : Build"
  make:
    chdir: "/usr/local/src/neovim"
    target: "CMAKE_BUILD_TYPE=Release"
