---
- name: "{{ ansible_distribution }} : Dependencies"
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake 
      - g++ 
      - pkg-config
      - unzip
      - curl
      - doxygen
      - curl
      - ansible-lint
      - ripgrep
    state: present
  become: true

- name: "Create downloads directory"
  file:
    path: "~/Downloads/neovim"
    state: directory

- name: "Clone neovim github repository"
  git:
    repo: "https://github.com/neovim/neovim"
    dest: "{{ ansible_user_dir }}/Downloads/neovim"
    clone: yes
    version: v0.10.3
    update: yes


      # If user specifies custom directory, then use extra flags
- name: "Run make"
  make:
    chdir: "{{ ansible_user_dir }}/Downloads/neovim"
    params:
      CMAKE_BUILD_TYPE: "RelWithDebInfo"
  become: false 

- name: "Run make install"
  make:
    target: "install"
    chdir: "{{ ansible_user_dir }}/Downloads/neovim"
  become: "yes"
